### ISSUE TITLE
[Refactor] Firebase 제거 (SPM 디펜던시 및 관련 코드)

### ISSUE THREAD

**Issue by ayaysir** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#115]
## 📸  Issue

Firebase 관련 부분 완전제거

- 파이어베이스가 연결되었던 부분은 나중에 API로 대체될수 있도록 TODO로 표시
- 뷰는 최대한으로 변경되지 않도록
- 9월 24일 23:59분까지 리뷰 승인 및 머지 목표 (풀리퀘가 아님)

## 📝  To-do

- [x] Firebase 패키지 디펜던시 제거
- [x] 관련 코드 제거
- [x] 네트워크에서 불러오는 데이터는 가능한 경우 모의 데이터로 대체
