### ISSUE TITLE
[Design] 아카이빙 탭 질문함 뷰 추가

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#124]
## 📸  Issue

아카이빙 탭 질문함 뷰 추가

## 📝  To-do

- [x] 전체/좋아요 바 만들기
- [x] 질문함 뷰 추가
- [x] 질문 검색 뷰 추가
- [x] 상단바 코드 리팩토링
