### ISSUE TITLE
[Feat] 오늘딥틱뷰 서버 통신

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#17]
## 📸  Issue

오늘딥틱뷰 서버 통신

## 📝  To-do

- [ ] 오늘의 주제 데이터 로직 정리
- [x] 일주일 캘린더 데이터 가져오기
- [ ] UI 업데이트
- [ ] 🚨 오늘딥틱뷰 행간 수정
