### ISSUE TITLE
[Feat] 커플 인증 기능

### ISSUE THREAD

**Issue by ivorrr987** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#18]
## 📸  Issue

Firebase FireStore를 이용하여 커플 인증 기능 및 커플 인증 뷰를 구현하려 합니다.
구체적인 방식은 개발 중에 달라질 수 있습니다.

## 📝  To-do

- [ ] FireStore 특정 데이터 get, set 작동 확인
- [ ] 커플 인증 기능 구현
- [ ] 커플 인증 뷰 개발
