### ISSUE TITLE
[Design] 사진 상세 뷰 레이아웃 제작

### ISSUE THREAD

**Issue by nylakim** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#24]
## 📸  Issue
- 사진 상세 뷰 구현

## 📝  To-do
- [x] 사진 상세 뷰 레이아웃 구현
- [x] 사진 들어갈 부분에 일단 아무 사진이나 url로 넣어뒀어요!
- [x] 해당하는 날짜, 몇 번째 딥틱인지 넘버링, 오늘의 주제, 사진 불러오기 → 변수로 빼두기
