### ISSUE TITLE
[Design] 프로필 뷰 레이아웃 제작 

### ISSUE THREAD

**Issue by nylakim** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#28]
## 📸  Issue
- 프로필 뷰 구현

## 📝  To-do

- [x] 프로필 뷰 레이아웃 구현
- [x] 유저 닉네임과 하트 아이콘 사이 간격 맞추기 (최대한)
- [x] 버전정보 및 개인정보처리방침은 일단 텍스트로 표기
