### ISSUE TITLE
[Feat] 카메라 업로드 부분 (1)

### ISSUE THREAD

**Issue by ayaysir** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#36]
## 📸  Issue

카메라와 Firebase간 통신 부분 일부 구현

## 📝  To-do

- [x] 촬영 완료 시 버튼을 통해 제출 - 파일 업로드
- [x] 오늘의 주제 불러오기
- [x] 유저의 데이터에 따라 왼/오른쪽 블라인드 나누기
