### ISSUE TITLE
[Feat] 오늘 업로드 상태에 따라 이미지 상태 구분

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#38]
## 📸  Issue

오늘 업로드 상태에 따라 이미지 상태 구분

## 📝  To-do

- [x] 이미지 업로드
- [x] 상태에 따른 재시작 버튼 추가
- [x] 완성되면 모든 버튼 없애기
- [x] 하루가 지날 시 photo 컬렉션 문서 추가
