### ISSUE TITLE
[Fix] [Design] 사진 상세 뷰 및 프로필 뷰 수정

### ISSUE THREAD

**Issue by nylakim** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#46]
## 📸  Issue

사진 상세 뷰 수정
프로필 뷰 수정

## 📝  To-do

- [x] 사진 상세 뷰 아이콘 수정
- [x] 사진 공유 및 저장 기능 추가 (계속 오류 남... 열심히 해볼게요...)
- [x] 프로필 뷰 레이아웃 수정 (유저 닉네임이랑 하트 아이콘 사이 간격 조정)
