### ISSUE TITLE
[Feat] 카메라 업로드 (3)

### ISSUE THREAD

**Issue by ayaysir** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#48]
## 📸  Issue

세부사항 구현 및 파일/경로이름 효율화

## 📝  To-do

- ~~가이드라인이 가로인 경우의 대응~~
- [x] 1회 업로드된 파일은 재업로드시 새로 생성하지 않고 해당 파일을 대체하도록 하기
- [x] isCompleted 인 경우 TodayDiptychView 새로고침해서 변경사항 반영되게 하기
- [x] UX 최적화 (로딩중인 경우 버튼이 함부로 눌리지 않게 처리 등)
