### ISSUE TITLE
[Feat] 오늘딥틱뷰 상세 수정 및 기능 추가

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#50]
## 📸  Issue

오늘딥틱뷰 상세 수정

## 📝  To-do

- [x] 오늘딥틱뷰 줄 수에 따라 패딩 조정
- [x] 완료된 날짜 탭할 시 이미지 상세뷰로 화면 전환
- [x] 아이폰 14 대응
- [x] 유저의 앨범과 연결
