### ISSUE TITLE
[Feat] 회원가입 기능 개발

### ISSUE THREAD

**Issue by ivorrr987** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#6]
## 📸  Issue
회원가입 기능 개발 (FirebaseAuth 이용)

## 📝  To-do
- [ ] 이메일 회원 가입 기능 개발
- [ ] (Optional) Apple 회원 가입 기능 개발
- [ ] (Optional) 카카오 회원 가입 기능 개발
