### ISSUE TITLE
[Design] 카메라 디자인: 툴팁 / 뒤로가기 버튼의 텍스트 / 업로드시 프로그레스 과정 텍스트로 표시

### ISSUE THREAD

**Issue by ayaysir** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#72]
## 📸  Issue

카메라 부분에서 UT에서 건의사항으로 받은 디자인 부분 내용들 보강

## 📝  To-do

- [x] 사진 촬영 직후 툴팁을 보여줘서 줌, 핀치, 로테이트에 대해 인지하도록 함 (최초 1회만 표시?)
- [x] 뒤로가기 버튼에 텍스트 추가
- [x] 업로드 진행시 로딩 화면에 프로그레스 과정을 텍스트로 표시
- [x] 플래시 버튼 토글
- [x] 하단 버튼 위치 조정
- [x] 전환 버튼, 라이브러리 버튼 크기 맞춤
- [x] 그 외 이슈 대응
