### ISSUE TITLE
[Fix] 프로필 뷰 디자인 변경

### ISSUE THREAD

**Issue by nylakim** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#78]
## 📸  Issue

프로필 뷰 디자인 변경

## 📝  To-do

- [x] 전체적인 레이아웃 수정
- [x] divider stroke 변경..!
- [x] 초대코드 정보 넣기
- [ ] (추가) currentUser가 무조건 왼쪽에 뜨는 이슈 해결
