### ISSUE TITLE
[Design] 오늘딥틱뷰 레이아웃 구현

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#8]
## 📸  Issue

오늘딥틱뷰 레이아웃 구현

## 📝  To-do

- [x] 오늘딥틱뷰 레이아웃 구현
- [x] 일주일 캘린더 구현
- [x] 캘린더 상태 구분
- [ ] 캘린더 부분 더미데이터 넣기
