### ISSUE TITLE
[Design] 카메라 디자인 수정

### ISSUE THREAD

**Issue by ayaysir** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#80]
## 📸  Issue

카메라 디자인

## 📝  To-do

- [x] 뒤로가기 레이블의 버튼 위치 조정
- [x] (+) 뒤로가기 레이블이 아니라 버튼으로 변경
- [x] 툴팁 팝업시 페이드인/아웃
- [x] 기타 디자인 이슈 수정
