### ISSUE TITLE
[Feat] 오늘딥틱뷰 위클리 캘린더 로직 변경 및 디자인 수정 반영

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MC3-Team8-Aing#83]
## 📸  Issue

오늘딥틱뷰 위클리 캘린더 로직 변경 및 디자인 수정

## 📝  To-do

- [x] 로직 다시 짜!
- [x] 수정된 디자인 반영하기
- [x] 상단 완료 딥틱 개수 연결
- [ ] 디자인 세부 수정 - tabView 높이 맞추기
- [x] 디자인 세부 수정 - divider 색
- [x] 디자인 세부 수정 - 상단 날짜 포맷
- [x] 둘다 완료되었을 때 alert 뜨게 하기
